# -*- coding: utf-8 -*-
"""Estudos_VisaoComputacional.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P_7fvFmPvvov_13fdmAeLAJ-dK6DH8N-
"""

import cv2
from google.colab.patches import cv2_imshow

img = cv2.imread('/content/drive/MyDrive/Machine Learning/Visão Computacional Guia Completo/My_Images/Pessoas/R.jpg')
img = cv2.resize(img,
                 (800,600))
#cv2_imshow(img)

img_cinza = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#cv2_imshow(img_cinza)

detector_facial = cv2.CascadeClassifier('/content/drive/MyDrive/Machine Learning/Visão Computacional Guia Completo/Cascades/haarcascade_frontalface_default.xml')
dtc = detector_facial.detectMultiScale(img_cinza,scaleFactor = 1.05,
                                       minNeighbors=7,
                                       minSize = (80,80))

for x,y,w,h in dtc:
  print(f'{w} - {h}')
  cv2.rectangle(img,(x,y),(x+w,y+h), (0,255,0),4)
cv2_imshow(img)